#pragma once

#define SECONDS_BETWEEN_ASTEROIDS 5
#define NUM_ASTEROID_SPAWN 5

#define ASTEROID_MIN_VELOCITY 1
#define ASTEROID_MAX_VELOCITY 10

#define SHIP_TURN_SPEED 5
#define SHIP_VELOCITY 7

#define BULLET_VELOCITY 30
#define MAX_BULLET_DISTANCE 1000

#define GAME_BOUNDS_X 2000
#define GAME_BOUNDS_Y 1000

#define NETWORK_PORT 50011
#define MAX_PLAYERS 4

#define TICKRATE_S 30.0
#define TICKRATE_MS 1000.0/TICKRATE_S